name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        mkdir release
        go mod download
        go build -ldflags "-s -w" -o ./release/f-proxy-agent-linux-amd64 fastgit.org/f-proxy-agent
  
    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: f-proxy-agent
        path: release/f-proxy-agent
    
